---
inputSchema:
  name: Input File Schema
  columns:
    - name: Provider ID
      type: string
    - name: Hospital Name
      type: string
    - name: Address
      type: string
    - name: City
      type: string
    - name: State
      type: string
    - name: ZIP Code
      type: string
    - name: County Name
      type: string
    - name: Phone Number
      type: string
    - name: Condition
      type: string
    - name: Measure ID
      type: string
    - name: Measure Name
      type: string
    - name: Score
      type: string
    - name: Sample
      type: string
    - name: Footnote
      type: string
    - name: Measure Start Date
      type: string
    - name: Measure End Date
      type: string

fileReaderOutput:
fileReader:
  name: Hospital File Reader
  fileResource:
    location: classpath:data/Timely and Effective Care - Hospital.csv
    linesToSkip: 1
  output: fileReaderOutput
  outputSchema: inputSchema

copyOutput:
copy:
  name: Copy
  input: fileReaderOutput
  outputs:
    - copyOutput

fileWriter:
  name: File Writer 1
  fileResource: file:output/output1.txt
  input: copyOutput
  inputSchema: inputSchema
