---
inputSchema:
  name: Input File Schema
  columns:
    - name: ProviderID
      type: string
    - name: HospitalName
      type: string
    - name: Address
      type: string
    - name: City
      type: string
    - name: State
      type: string
    - name: ZIPCode
      type: string
    - name: CountyName
      type: string
    - name: PhoneNumber
      type: string
    - name: HospitalCondition
      type: string
    - name: MeasureID
      type: string
    - name: MeasureName
      type: string
    - name: Score
      type: string
    - name: Sample
      type: string
    - name: Footnote
      type: string
    - name: MeasureStartDate
      type: string
    - name: MeasureEndDate
      type: string

fileReaderOutput:
fileReader:
  name: Hospital File Reader
  fileResource:
    location: classpath:data/Timely and Effective Care - Hospital.csv
    linesToSkip: 1
  output: fileReaderOutput
  outputSchema: inputSchema

databaseWriter:
  name: Database Writer
  input: fileReaderOutput
  inputSchema: inputSchema
  dataSource: dataSource
  insertInto: hospital

